# -*- coding: utf-8 -*-
"""prepare data and run models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLaKrI3zRv5_VQg0N75gA61c6h__PjEn
"""

def shift_features_for_horizon(incoming_data, horizon_hours):
    """
    Shifts live time-series feature keys to match their historical lag equivalents
    based on the predictive horizon.

    Example for a 3-hour horizon:
      'sensor_turbidity'      -> 'sensor_turbidity_lag3'
      'sensor_turbidity_lag1' -> 'sensor_turbidity_lag4'
    """
    shifted_data = {}

    for key, value in incoming_data.items():
        # Split by '_lag' to separate the base feature name from its index number
        if "_lag" in key:
            base_name, current_lag = key.split("_lag")
            new_lag = int(current_lag) + horizon_hours
            new_key = f"{base_name}_lag{new_lag}"
        else:
            # This is the current/live step (e.g., 'sensor_turbidity')
            new_key = f"{key}_lag{horizon_hours}"

        shifted_data[new_key] = value

    return shifted_data

def run_classification_model(data, model, scaler_dict, feature_cols):
    print("\n[Running Classification Model...]")

    # 1. Convert your input data dictionary into a DataFrame matching model features
    df = pd.DataFrame([data])
    df = df[feature_cols]  # Ensure columns match the training order

    # 2. Scale your data if your model configuration requires it
    # (Assuming you need to scale. Adjust based on your 'config.json')
    # df_scaled = scaler_dict['scaler'].transform(df)

    # 3. Make the actual prediction
    prediction = model.predict(df)[0]

    # Check if predict_proba is available for confidence
    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(df)[0]
        confidence = max(probabilities) * 100
        return f"Class {prediction} (Confidence: {confidence:.2f}%)"

    return f"Class Prediction: {prediction}"

def run_regression_model(data, model, scaler_dict, feature_cols, horizon_name):
    print(f"\n[Running Regression Model for {horizon_name} Horizon...]")

    # 1. Convert input data to match features
    df = pd.DataFrame([data])
    df = df[feature_cols]

    # 2. Make the actual prediction
    prediction = model.predict(df)[0]

    return f"Predicted Value for {horizon_name}: {prediction:.4f}"