# -*- coding: utf-8 -*-
"""prepare data and run models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fLaKrI3zRv5_VQg0N75gA61c6h__PjEn
"""

import pandas as pd
import numpy as np

def shift_features_for_horizon(df, horizon_hours):
    """
    Shifts live time-series feature columns to match their historical lag
    equivalents based on the predictive horizon in a DataFrame.
    """
    rename_map = {}

    for col in df.columns:
        if "_lag" in col:
            # Extract base name and current lag index
            base_name, current_lag = col.rsplit("_lag", 1)
            new_key = f"{base_name}_lag{int(current_lag) + horizon_hours}"
        else:
            # Handle the base column (e.g., 'sensor_turbidity' -> 'sensor_turbidity_lag3')
            new_key = f"{col}_lag{horizon_hours}"

        rename_map[col] = new_key

    return df.rename(columns=rename_map)

def run_classification_model(data, model, scaler_dict, feature_cols):
    print("\n[Running Classification Model...]")

    # 1. Convert your input data dictionary into a DataFrame matching model features
    df = data[feature_cols]  # Ensure columns match the training order
    df_scaled = df.copy()
    # 2. Scale your data if your model configuration requires it
    for key, scaler in scaler_dict.items():
        # Check if the scaler key exists in your feature columns
        # This assumes your scaler keys match the column names or logical groups
        if key in df.columns:
            df_scaled[[key]] = scaler.transform(df[[key]])

    # 3. Make the actual prediction
    prediction = model.predict(df_scaled)[0]

    # Check if predict_proba is available for confidence
    if hasattr(model, "predict_proba"):
        probabilities = model.predict_proba(df)[0]
        confidence = max(probabilities) * 100
        return f"Class {prediction} (Confidence: {confidence:.2f}%)"

    return f"Class Prediction: {prediction}"

def run_regression_model(data, model, scaler_dict, feature_cols, horizon_name):
    print(f"\n[Running Regression Model for {horizon_name} Horizon...]")

    # 1. Convert input data to match features
    df = data[feature_cols]
    df_scaled = df.copy()
    # 2. Scale your data if your model configuration requires it
    for key, scaler in scaler_dict.items():
        if key in df.columns:
            df_scaled[[key]] = scaler.transform(df[[key]])

    # 2. Make the actual prediction
    prediction_scaled = model.predict(df_scaled)[0]

    # 3. Convert prediction to real turbidity data.
    prediction_scaled = prediction_scaled.reshape(-1, 1)
    prediction = scaler_dict['sensor_turbidity'].inverse_transform(prediction_scaled).flatten()
    return f"Predicted Value for {horizon_name}: {prediction[0]:.4f}"